# Generated by Django 5.0.6 on 2024-07-02 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myrole", "0002_alter_customuser_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_hod",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_principal",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="is_student",
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hod", "Head of Department"),
                    ("principal", "Principal"),
                    ("student", "Student"),
                    ("staff", "Staff"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="hod",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "hod"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="principal",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "principal"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "staff"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                limit_choices_to={"role": "student"},
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
